from pathlib import Path

import joblib
import pandas as pd
import streamlit as st


# ============================================================
# 1. PROJECT PATHS
# ============================================================

BASE_DIR = Path(__file__).resolve().parents[1]

MODEL_DIR = BASE_DIR / "models"
DATA_PATH = BASE_DIR / "data" / "Dataset.csv"


# ============================================================
# 2. PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="CarValue",
    page_icon="🚗",
    layout="centered"
)


# ============================================================
# 3. LOAD MODEL + DATA
# ============================================================

@st.cache_resource
def load_model():

    model = joblib.load(
        MODEL_DIR / "car_price_model_tuned.joblib"
    )

    options = joblib.load(
        MODEL_DIR / "input_options.joblib"
    )

    return model, options


@st.cache_data
def load_dataset():

    df = pd.read_csv(DATA_PATH)

    return df


try:

    model, options = load_model()

    df = load_dataset()

except FileNotFoundError:

    st.error(
        "Required model or dataset files were not found."
    )

    st.stop()


# ============================================================
# 4. HEADER
# ============================================================

st.title("🚗 CarValue")

st.subheader(
    "Used Car Price Prediction"
)

st.write(
    "Estimate the market value of a used car "
    "using Machine Learning."
)


st.divider()


# ============================================================
# 5. CAR DETAILS
# ============================================================

st.header("Enter Car Details")


# ------------------------------------------------------------
# Manufacturing Year
# ------------------------------------------------------------

year = st.number_input(
    "Manufacturing Year",
    min_value=1990,
    max_value=2026,
    value=2020,
    step=1
)


# ------------------------------------------------------------
# Brand
# ------------------------------------------------------------

brand = st.selectbox(
    "Car Brand",
    options["brand"]
)


# ============================================================
# FILTER MODELS BASED ON BRAND
# ============================================================

brand_models = (
    df[
        df["brand"].astype(str) == str(brand)
    ]["model_name"]
    .dropna()
    .astype(str)
    .unique()
    .tolist()
)

brand_models = sorted(brand_models)


# ------------------------------------------------------------
# Model
# ------------------------------------------------------------

if len(brand_models) > 0:

    model_name = st.selectbox(
        "Car Model",
        brand_models
    )

else:

    model_name = st.selectbox(
        "Car Model",
        options["model_name"]
    )


# ------------------------------------------------------------
# Kilometres
# ------------------------------------------------------------

distance = st.number_input(
    "Distance Travelled (km)",
    min_value=0,
    max_value=1000000,
    value=30000,
    step=1000
)


# ------------------------------------------------------------
# Fuel Type
# ------------------------------------------------------------

fuel_type = st.selectbox(
    "Fuel Type",
    options["fuel_type"]
)


# ------------------------------------------------------------
# City
# ------------------------------------------------------------

city = st.selectbox(
    "City",
    options["city"]
)


# ============================================================
# 6. PREDICTION
# ============================================================

st.divider()


if st.button(
    "🚗 Predict Car Price",
    use_container_width=True
):

    input_data = pd.DataFrame([{

        "year": year,

        "brand": brand,

        "model_name": model_name,

        "distance_travelled(kms)": distance,

        "fuel_type": fuel_type,

        "city": city

    }])


    # Make prediction

    prediction = model.predict(
        input_data
    )[0]


    # ========================================================
    # RESULT
    # ========================================================

    st.success(
        "Prediction generated successfully!"
    )


    st.metric(
        label="Estimated Car Price",
        value=f"{prediction:,.0f}"
    )


    st.info(
        "The estimated value is generated by the "
        "CarValue machine-learning model. Actual "
        "market prices can vary based on condition, "
        "ownership history, location and other factors."
    )


# ============================================================
# 7. FOOTER
# ============================================================

st.divider()

st.caption(
    "CarValue • Used Car Price Prediction "
    "using Machine Learning"
)